services:
  dkgservicenode:
    container_name: dkg_service_node
    image: ${DOCKER_REGISTRY-}dkgservicenode
    build:
      context: .
      dockerfile: dkgServiceNode/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - dkgservice_db

  dkgnode1:
    container_name: dkg_node_1
    image: ${DOCKER_REGISTRY-}dkgnode
    environment:
      - DKG_SERVICE_NODE_URL=http://dkg_service_node:8080
      - DKG_NODE_NAME=First node
      - DKG_NODE_POLLING_INTERVAL=3500
        # bonus pretty melt journey project siren harsh pioneer spin holiday chase harvest
      - DKG_NODE_SOLANA_ADDRESS=4KFR297L24YnX9A232mQpprhCaJ4Y5CA57JFXCCHrjqS
    build:
      context: .
      dockerfile: dkgNode/Dockerfile
    depends_on:
      - dkgservicenode

  dkgnode2:
    container_name: dkg_node_2
    image: ${DOCKER_REGISTRY-}dkgnode
    environment:
      - DKG_SERVICE_NODE_URL=http://dkg_service_node:8080
      - DKG_NODE_NAME=Second node
        # wild dizzy good quantum purpose crazy evidence oak give pass describe wild
      - DKG_NODE_SOLANA_ADDRESS=AKoAnVhRtm7c35UMWZUVzktdD7Tq1nZpRVminmHwFER6
    build:
      context: .
      dockerfile: dkgNode/Dockerfile
    depends_on:
      - dkgservicenode

  dkgnode3:
    container_name: dkg_node_3
    image: ${DOCKER_REGISTRY-}dkgnode
    environment:
      - DKG_SERVICE_NODE_URL=http://dkg_service_node:8080
      - DKG_NODE_NAME=Third node
        # tail analyst dream tornado simple brown mad same small wagon mammal fun
      - DKG_NODE_SOLANA_ADDRESS=EgcYjVC6wBoUx4gUspYDjiKCfV9WqfV5iTk3A9iuKi41
    build:
      context: .
      dockerfile: dkgNode/Dockerfile
    depends_on:
      - dkgservicenode

  dkgnode4:
    container_name: dkg_node_4
    image: ${DOCKER_REGISTRY-}dkgnode
    environment:
      - DKG_SERVICE_NODE_URL=http://dkg_service_node:8080
      - DKG_NODE_NAME=Fourth node
        # ramp marble that cactus fee field shadow brand just father light sport
      - DKG_NODE_SOLANA_ADDRESS=8iVGKCdSkzyrnLKzeGnbJYSfQsdV2NsdyzQkTDq3YvfV
    build:
      context: .
      dockerfile: dkgNode/Dockerfile
    depends_on:
      - dkgservicenode

  dkgnode5:
    container_name: dkg_node_5
    image: ${DOCKER_REGISTRY-}dkgnode
    environment:
      - DKG_SERVICE_NODE_URL=http://dkg_service_node:8080
      - DKG_NODE_NAME=Fifth node
      - DKG_NODE_DIE_ON_STEP_TWO=Yes
    build:
      context: .
      dockerfile: dkgNode/Dockerfile
    depends_on:
      - dkgservicenode

  dkgservice_db:
    container_name: dkgservice_db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dkgservice
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  pgdata: {}
